### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by whitesheepsheep** [YOLOSHOW/YOLOSHOW#39]
Traceback (most recent call last):
  File "D:\exercise\YOLOSHOW-master1\YOLOSHOW-master\main.py", line 24, in <module>
    yoloshow = yoloshowWindow()
  File "D:\exercise\YOLOSHOW-master1\YOLOSHOW-master\yoloshow\Window.py", line 17, in __init__
    super(YOLOSHOWWindow, self).__init__()
  File "D:\exercise\YOLOSHOW-master1\YOLOSHOW-master\yoloshow\YOLOSHOW.py", line 32, in __init__
    self.ui.setupUi(self)
  File "D:\exercise\YOLOSHOW-master1\YOLOSHOW-master\ui\YOLOSHOWUI.py", line 1340, in setupUi
    self.model_box = ComboBox(self.Model_QF_2)
  File "C:\Users\51433\anaconda3\envs\yolov5\lib\site-packages\qfluentwidgets\components\widgets\combo_box.py", line 377, in __init__
    super().__init__(parent=parent)
  File "C:\Users\51433\anaconda3\envs\yolov5\lib\site-packages\qfluentwidgets\components\widgets\combo_box.py", line 63, in __init__
    super().__init__(parent=parent)
TypeError: arguments did not match any overloaded call:
  QPushButton(parent: Optional[QWidget] = None): argument 'parent' has unexpected type 'PySide6.QtWidgets.QWidget'
  QPushButton(text: Optional[str], parent: Optional[QWidget] = None): not enough arguments
  QPushButton(icon: QIcon, text: Optional[str], parent: Optional[QWidget] = None): not enough arguments
  为什么main.py运行过后是这样报错呀

**Comment by SwimmingLiu** [comment]
```
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
