### ISSUE TITLE
大佬帮忙看下：ValueError

### ISSUE THREAD

**Issue by xiaoming-gong** [YOLOSHOW/YOLOSHOW#43]
Error calling Python override of QThread::run(): Traceback (most recent call last):
  File "C:\Users\GGM\Desktop\YOLOSHOW-master\yolocode\yolov8\YOLOv8Thread.py", line 89, in run
    self.setup_model(self.new_model_name)
  File "C:\Users\GGM\Desktop\YOLOSHOW-master\yolocode\yolov8\YOLOv8Thread.py", line 277, in setup_model
    self.model = AutoBackend(
  File "D:\Anaconda\envs\DL\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\GGM\Desktop\YOLOSHOW-master\models\common.py", line 2713, in __init__
    (
ValueError: not enough values to unpack (expected 16, got 14)

**Comment by xiaoming-gong** [comment]
我已经解决了，使用最新的ultralytics库
